### ISSUE TITLE
TypeScript typings not available in non-Windows dev environments

### ISSUE THREAD

**Issue by zenflow** [zenflow/generate-ctrl-c-event#9]
@kazarmy brought this issue up in https://github.com/zenflow/generate-ctrl-c-event/pull/8#issue-603535721:

> This pr removes the os constraint because the type definitions included in the package are needed for type checking on Linux of multi-platform scripts using it, and removing the os constraint allows installation of the package on Linux without have to use --force.
>
> Maybe this is a situation where the type definitions are better placed on the DefinitelyTyped monorepo? 

The reason for the "os" constraint is so that this package and it's dependencies (particularly the **huge** `ffi-napi` dependency) don't get installed in environments where they won't be used. 

It is an optimization that I would like to keep, since otherwise, it becomes harder to justify using this package in cross-platform packages/programs due to the heavy cost to install size and complexity (`ffi-napi` is a native Node.js add-on with binaries) in environments that won't even benefit from it.

If we made the `ffi-napi` package an optional **peer** dependency, so you would optionally install it alongside this package, then we wouldn't need the "os" constraint, but I don't think that is the best way to go. See https://github.com/zenflow/generate-ctrl-c-event/issues/6#issuecomment-810704419

So yeah, I think DefinitelyTyped is the way to go to get the types available in non-Windows dev environments.

@kazarmy If you or anyone wants to add the type definitions there, that would be awesome

I guess then we could remove them from this package in a new major release

TBH I'm using this package in TS and developing on Linux and I just accepted that I don't have types for these functions. I'm only calling one of the functions, in one place, and not even looking at the result. 😄

**Comment by kazarmy** [comment]
> @kazarmy If you or anyone wants to add the type definitions there, that would be awesome

See DefinitelyTyped/DefinitelyTyped#52149. I've put you as one of the co-maintainers.

> I guess then we could remove them from this package in a new major release

If you do so, could you just do a point release? Otherwise I'd have to update the typings version on DefinitelyTyped.

**Comment by zenflow** [comment]
@kazarmy Type definitions have now been removed from this package and published in `@types/generate-ctrl-c-event`. 
If you can confirm everything is now working as expected, we can close this issue.

**Comment by kazarmy** [comment]
Yes, everything works as expected. Thanks for the help!

**Comment by zenflow** [comment]
@kazarmy No problem! Give the project a star if you like it ;D

**Comment by kazarmy** [comment]
Done! :smile:
